### PR TITLE
Added Chapter 02, Question 09, 10.

### PR DESCRIPTION
**Pull request by SaqibAMA**
Added chp2_09a.asm
Added chp2_09b.asm
Added chp2_09c.asm
Added chp2_10.asm

### CODE REVIEW

**Comment by harismuneer** [comment]
@PySaqib awesome stuff! Can you also get these solutions reviewed by two other members. I want the quality to be high since many students will use your solutions as foundation.

**Comment by SaqibAMA** [comment]
@nabeegh-ahmed @ubaidmalik113 @farhana1i can you guys kindly run these programs on your systems and verify if they are correct? Thanks.

**Comment by ubaidmalik113** [comment]
Thank you @PySaqib for inviting me to review this. I ran the programs on my Dosbox and they worked fine 😊


**Output for the Question 10**

20^2 = 190h

image

**Review by hifarhanali — COMMENTED** [review]
@PySaqib Thank you for giving me this honor. I review these questions on my local machine and dry run as well. They give the expected outputs. You absolutely have written a well-commented code. Excellent!

**Comment by Nabeegh-Ahmed** [comment]
I ran the code on my machine. It works really well. The code is well commented, it is efficient and very well written. @harismuneer safe to merge this commit with main.

**Comment by harismuneer** [comment]
Thank you guys @Nabeegh-Ahmed @PySaqib @ubaidmalik113 @farhana1i . Also, you can reveiw the solutions already in the repository for any errors and generate PRs for them. Highly appreciate your support!

**Comment by hifarhanali** [comment]
> Thank you guys @Nabeegh-Ahmed @PySaqib @ubaidmalik113 @farhana1i. Also, you can review the solutions already in the repository for any errors and generate PRs for them. Highly appreciate your support!

@harismuneer sure, we will.

**Pull request merged**
