### PR TITLE
Upload solution of chp9Q3, chp9Q8 of Bilal Hashmi Book Assembly Language

### PR DESCRIPTION
**Pull request by hifarhanali**
I have written these codes in x86 assembly language. @Nabeegh-Ahmed and @PySaqib Kindly review these questions.

### CODE REVIEW

**Comment by SaqibAMA** [comment]
@farhana1i I think these are valid and efficient solutions. I ran them on my local machine and they produced the target output. Good work.

**Comment by Nabeegh-Ahmed** [comment]
@farhana1i I ran these files on my machine and carefully analyzed the questions in the book. The code in your commit is well documented and is an efficient solution. It is by no doubt that this commit should be merged with the main branch.

**Comment by hifarhanali** [comment]
@Nabeegh-Ahmed and @PySaqib Thank you for your time.

**Comment by harismuneer** [comment]
Thank you everyone for this contribution. Looking forward to many more! :)

**Pull request merged**
